name: conditional-workflow
on:
  branches:
    - devel

jobs:
  echo-dir:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        uses: actions/checkout@v3

      -name: ls-code
       run: ls -lFa
