name: conditional-workflow
on:
  push:
    branches:
      - devel

jobs:
  echo-dir:
    name: echo-files
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        uses: actions/checkout@v3

      - name: ls-code
        run: ls -lFa
