name: workflows-demo
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t gh_ci_image .

      - name: Run tests from Docker container
        run: docker run --rm -v $PWD:/workspace -w /workspace gh_ci_image:latest
