name: my-task
on: push

jobs:
  hi:
   name: hello
   runs-on: ubuntu-latest
   steps:
     - name: checkout-code
       uses: actions/checkout@v3
       with:
         fetch-depth: 0

     - name: diff
       run:  echo "CHANGED_FILES=$(git diff --name-only include/ ${{ github.event.before }}..${{ github.event.after }});
                   echo $CHANGED_FILES"
     - name: hw
       run: echo "Hello world!"
